version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    timezone: America/Los_Angeles
    day: tuesday
  target-branch: "develop"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: onelogin/php-saml
    versions:
    - ">= 4"
    - "< 5"
  - dependency-name: phpunit/phpunit
    versions:
    - ">= 8.a"
    - "< 9"
  - dependency-name: phpunit/phpunit
    versions:
    - ">= 9.a"
    - "< 10"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    timezone: America/Los_Angeles
    day: tuesday
  target-branch: "develop"
  open-pull-requests-limit: 99
- package-ecosystem: "github-actions"
  target-branch: "develop"
  directory: "/"
  schedule:
    interval: daily