---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: wp-saml-auth
  description: Rock-solid SAML authentication for WordPress built on a modern foundation.
  annotations:
    github.com/project-slug: pantheon-systems/wp-saml-auth
spec:
  type: service
  lifecycle: production
  owner: site-experience
